services:
  wolapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: '8080'
    network_mode: host
    ports: # only windows respects this, since network_mode: host
      - 8080:8080
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./wol.db
        target: /app/wol.db
